name: "custom-thumbnail-action"
author: deep5050
description: "Cereate custom thumbnails out of all the original images recursively"

inputs:
  github_token:
    description: "GITHUB_TOKEN secret < automatically provided by Github , you don't need to set up >"
    required: true

  base_height_width:
    description: "base height/width to be maintained"
    default: "500"
    required: false

   inplace:
    description: "Replace original file with the resultant one"
    default: False
    required: false

  pull_request_branch:
    description: "Branch that the action will target on pull_request. Defaults to GITHUB_BASE_REF."
    default: ""
    required: false

  target_repository:
    description: "Repository that the report will be pushed on. Defaults to the current repository."
    default: ""
    required: false

  pull_request_repository:
    description: "Repository that the action will target on pull_request. Defaults to TARGET_REPOSITORY"
    default: ""
    required: false

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "image"
  color: "red"
