name: test

on: [push]

jobs:

  build:

    name: custom-thumbnail

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: custom-thumbnail

        uses: deep5050/custom-thumbnail@master

        with:

          github_token: ${{ secrets.GITHUB_TOKEN}}

          inplace: "disable"
          base_height_width: "400"
          keep_dir_structure: "enable"


      - name: Commit & Push changes

        uses: mikeal/publish-to-github-action@master

        env:

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
